
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class Addcustomer extends javax.swing.JFrame {
   Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
   
  
    /**
     * Creates new form Addcustomer
     */
    public Addcustomer() {
        initComponents();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cust_name = new javax.swing.JTextField();
        meterno = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        canclebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 250, 270, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Meter No:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 330, 250, 42);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 410, 200, 42);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 490, 120, 42);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 570, 120, 42);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(758, 260, 34, 0);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 650, 250, 42);

        Cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_nameActionPerformed(evt);
            }
        });
        Cust_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cust_nameKeyPressed(evt);
            }
        });
        getContentPane().add(Cust_name);
        Cust_name.setBounds(940, 250, 320, 40);

        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        getContentPane().add(meterno);
        meterno.setBounds(940, 330, 320, 40);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(940, 410, 320, 40);

        City.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CityKeyPressed(evt);
            }
        });
        getContentPane().add(City);
        City.setBounds(940, 490, 320, 40);

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(940, 570, 320, 40);

        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenoKeyPressed(evt);
            }
        });
        getContentPane().add(phoneno);
        phoneno.setBounds(940, 650, 320, 40);

        submitbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitbtn);
        submitbtn.setBounds(630, 750, 120, 50);

        canclebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        canclebtn.setText("Cancle");
        canclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclebtnActionPerformed(evt);
            }
        });
        getContentPane().add(canclebtn);
        canclebtn.setBounds(1140, 750, 120, 50);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Customer");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(792, 20, 304, 56);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1930, 107);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Id:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 170, 220, 42);
        getContentPane().add(customerid);
        customerid.setBounds(940, 170, 170, 40);

        Update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(800, 750, 110, 50);

        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(980, 750, 110, 50);

        Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(1140, 170, 120, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addcustomer.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 2100, 1000);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1010, 40));

        Addcustomer.setBorder(null);
        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Calculatebill.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DepositeDetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customerdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        meterdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
      try{
         String insert = db.Insert("insert into Addcustomer(customerid,customername, meterno, Address, city, Email, Phoneno )values('"+customerid.getText()+"','"+Cust_name.getText().toString()+"','"+meterno.getText()+"','"+address.getText().toString()+"','"+City.getText().toString()+"','"+Email.getText().toString()+"','"+phoneno.getText().toString()+"')");
       JOptionPane.showMessageDialog(null, insert);
        }
       catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex.toString());
        }                                      
         
    }//GEN-LAST:event_submitbtnActionPerformed

    private void canclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclebtnActionPerformed
        // TODO add your handling code here:
        Homepage obj=new Homepage();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_canclebtnActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void Cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_nameActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
      try{
          String update = db.update("update Addcustomer set customername='"+Cust_name.getText().toString()+"',meterno='"+meterno.getText().toString()+"',Address='"+address.getText().toString()+"',city='"+City.getText().toString()+"',Email='"+Email.getText().toString()+"',Phoneno='"+phoneno.getText().toString()+"' where  customerid='"+customerid.getText()+"' ");
          JOptionPane.showMessageDialog(null, update);
      }  
      catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex.toString());
          
      }
    }//GEN-LAST:event_UpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
               try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from addcustomer where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                Cust_name.setText(rs.getString("customername"));
                meterno.setText(rs.getString("meterno"));
                address.setText(rs.getString("Address"));
                City.setText(rs.getString("city"));
                Email.setText(rs.getString("Email"));
                phoneno.setText(rs.getString("Phoneno"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }

    }//GEN-LAST:event_SearchActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         try
        {
            String delete=db.delete("delete from Addcustomer where customerid='"+customerid.getText()+"' ");
     JOptionPane.showMessageDialog(null,delete);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        // TODO add your handling code here:
        String var = Email.getText();
        
        Pattern pattern;
        Matcher matcher;
        
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        pattern = Pattern.compile(EMAIL_PATTERN);
        
        matcher = pattern.matcher(var);
        
        
        if(matcher.matches())
        {
        
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Envalid Email");
        }
        
    }//GEN-LAST:event_EmailFocusLost

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_meternoKeyPressed

    private void phonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_phonenoKeyPressed

    private void Cust_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cust_nameKeyPressed
        // TODO add your handling code here:
          char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_Cust_nameKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_addressKeyPressed

    private void CityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CityKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_CityKeyPressed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcustomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Cust_name;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JButton Delete;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JTextField address;
    private javax.swing.JButton canclebtn;
    private javax.swing.JTextField customerid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JTextField meterno;
    private javax.swing.JTextField phoneno;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
