
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class Calculatebill extends javax.swing.JFrame {
     Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
   
    /**
     * Creates new form Calculatebill
     */
    public Calculatebill() {
        initComponents();
         this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        units = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox();
        submitbtn = new javax.swing.JButton();
        canclebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        meterno = new javax.swing.JTextField();
        Pick = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TotalBill = new javax.swing.JTextField();
        Calculate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        month2 = new javax.swing.JComboBox();
        TotalBill2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Calculate2 = new javax.swing.JButton();
        Update2 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        canclebtn2 = new javax.swing.JButton();
        search2 = new javax.swing.JButton();
        submitbtn2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Meter Number:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 340, 290, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 410, 130, 42);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(960, 410, 340, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 480, 140, 42);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(960, 480, 340, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Units Consumed:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 550, 280, 42);

        units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitsActionPerformed(evt);
            }
        });
        units.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitsKeyPressed(evt);
            }
        });
        getContentPane().add(units);
        units.setBounds(960, 550, 340, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Month:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 630, 120, 28);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octombar", "November", "December", " " }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(960, 620, 340, 40);

        submitbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitbtn.setText("Submit ");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitbtn);
        submitbtn.setBounds(670, 790, 110, 60);

        canclebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        canclebtn.setText("Cancle");
        canclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclebtnActionPerformed(evt);
            }
        });
        getContentPane().add(canclebtn);
        canclebtn.setBounds(1240, 790, 100, 60);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculate Electricity Bill");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(736, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(714, 714, 714))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1950, 100);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 556, 0, 85);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Customer Id:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(690, 270, 220, 42);

        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });
        getContentPane().add(customerid);
        customerid.setBounds(960, 270, 180, 40);

        Update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(960, 790, 110, 60);

        search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(815, 790, 110, 60);

        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1101, 790, 100, 60);

        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                meternoFocusGained(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        getContentPane().add(meterno);
        meterno.setBounds(960, 340, 340, 40);

        Pick.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Pick.setText("Pick");
        Pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickActionPerformed(evt);
            }
        });
        getContentPane().add(Pick);
        Pick.setBounds(1180, 270, 120, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Total Bill:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(690, 700, 160, 42);

        TotalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBillActionPerformed(evt);
            }
        });
        TotalBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TotalBillKeyPressed(evt);
            }
        });
        getContentPane().add(TotalBill);
        TotalBill.setBounds(960, 700, 200, 40);

        Calculate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });
        getContentPane().add(Calculate);
        Calculate.setBounds(1180, 700, 120, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic1.jpg"))); // NOI18N
        jLabel20.setText("jLabel9");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 100, 1950, 880);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Units Consumed:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(256, 344, 134, 22);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Month:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(256, 395, 58, 22);

        month2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octombar", "November", "December", " " }));
        month2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month2ActionPerformed(evt);
            }
        });
        getContentPane().add(month2);
        month2.setBounds(422, 398, 268, 20);

        TotalBill2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TotalBill2KeyPressed(evt);
            }
        });
        getContentPane().add(TotalBill2);
        TotalBill2.setBounds(422, 454, 120, 20);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Total Bill:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(256, 451, 78, 22);

        Calculate2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Calculate2.setText("Calculate");
        Calculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate2ActionPerformed(evt);
            }
        });
        getContentPane().add(Calculate2);
        Calculate2.setBounds(569, 453, 83, 23);

        Update2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update2.setText("Update");
        Update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update2ActionPerformed(evt);
            }
        });
        getContentPane().add(Update2);
        Update2.setBounds(473, 507, 89, 31);

        delete2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete2.setText("Delete");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        getContentPane().add(delete2);
        delete2.setBounds(594, 507, 81, 31);

        canclebtn2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        canclebtn2.setText("Cancle");
        canclebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclebtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(canclebtn2);
        canclebtn2.setBounds(693, 507, 94, 31);

        search2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search2.setText("Search");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        getContentPane().add(search2);
        search2.setBounds(355, 507, 85, 31);

        submitbtn2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitbtn2.setText("Submit ");
        submitbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(submitbtn2);
        submitbtn2.setBounds(229, 507, 93, 31);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1010, 40));

        Addcustomer.setBorder(null);
        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Calculatebill.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DepositeDetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customerdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        meterdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        try{
        String var1=month.getSelectedItem().toString();
        String insert=db.Insert("insert into calculatebill(customerid,meterno, name, address, units, month,Totalbill)values ('"+customerid.getText()+"','"+meterno.getText()+"','"+Name.getText().toString()+"','"+address.getText().toString()+"','"+units.getText().toString()+"','"+var1+"','"+TotalBill.getText().toString()+"')");
        JOptionPane.showMessageDialog(null, insert);
        }
       catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex.toString());
        }                                      
    }//GEN-LAST:event_submitbtnActionPerformed

    private void canclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclebtnActionPerformed
        // TODO add your handling code here:
        Homepage obj=new Homepage();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_canclebtnActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
      try{
          String update = db.update("update Calculatebill set meterno='"+meterno.getText()+"',name='"+Name.getText().toString()+"',address='"+address.getText().toString()+"',units='"+units.getText().toString()+"', month='"+month.getSelectedItem().toString()+"',Totalbill='"+TotalBill.getText().toString()+"' where customerid='"+customerid.getText()+"'");
          JOptionPane.showMessageDialog(null, update);
      }  
      catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex.toString());
          
      }   
    }//GEN-LAST:event_UpdateActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from calculatebill where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                Name.setText(rs.getString("name"));
                meterno.setText(rs.getString("meterno"));
                address.setText(rs.getString("address"));
                units.setText(rs.getString("units"));
                month.setSelectedItem(rs.getString("month"));
                TotalBill.setText(rs.getString("Totalbill"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }

    
    }//GEN-LAST:event_searchActionPerformed

    private void PickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from Addcustomer where customerid = '"+customerid.getText()+"' ";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                Name.setText(rs.getString("customername"));
                meterno.setText(rs.getString("meterno"));
                address.setText(rs.getString("Address"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }

    
    }//GEN-LAST:event_PickActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String Delete=db.delete("delete from Calculatebill where customerid='"+customerid.getText()+"' ");
     JOptionPane.showMessageDialog(null,Delete);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void unitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitsActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
        
      int unit=Integer.parseInt(units.getText());
       
      
      if(unit<=100)
      {
      Double Totalbill=3.46*unit;
      TotalBill.setText(""+Totalbill);
      }
      else if(unit>100){
       Double Totalbill=7.43*unit;
      TotalBill.setText(""+Totalbill);  
        
      }
 
       

    }//GEN-LAST:event_CalculateActionPerformed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_meternoActionPerformed

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_meternoKeyPressed

    private void unitsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitsKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_unitsKeyPressed

    private void TotalBillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalBillKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_TotalBillKeyPressed

    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_NameKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_addressKeyPressed

    private void month2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month2ActionPerformed

    private void TotalBill2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalBill2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalBill2KeyPressed

    private void Calculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculate2ActionPerformed

    private void Update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update2ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete2ActionPerformed

    private void canclebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclebtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canclebtn2ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search2ActionPerformed

    private void submitbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitbtn2ActionPerformed

    private void TotalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalBillActionPerformed

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void meternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meternoFocusGained

    }//GEN-LAST:event_meternoFocusGained

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatebill().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JButton Calculate;
    private javax.swing.JButton Calculate2;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Pick;
    private javax.swing.JTextField TotalBill;
    private javax.swing.JTextField TotalBill2;
    private javax.swing.JButton Update;
    private javax.swing.JButton Update2;
    private javax.swing.JTextField address;
    private javax.swing.JButton canclebtn;
    private javax.swing.JButton canclebtn2;
    private javax.swing.JTextField customerid;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JTextField meterno;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox month2;
    private javax.swing.JButton search;
    private javax.swing.JButton search2;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton submitbtn2;
    private javax.swing.JTextField units;
    // End of variables declaration//GEN-END:variables
}
