
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;  
import javax.swing.table.DefaultTableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class Customerdetails extends javax.swing.JFrame {
Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
   DefaultTableModel model = new DefaultTableModel();
   
   PreparedStatement pst = null;
   ResultSet rs = null;
   
  
    public Customerdetails() 
    {
        initComponents();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
        try
        {
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root");
            String q="select * from addcustomer";
            pst=cn.prepareStatement(q);
            rs=pst.executeQuery();
            
       
            while(rs.next())
            {
                String customerid = rs.getString("customerid");
                String customername = rs.getString("customername");
                String meterno = rs.getString("meterno");
                String Address = rs.getString("Address");
                String city = rs.getString("city");
                String Email = rs.getString("Email");
                String Phoneno = rs.getString("Phoneno"); 
                
                String tbdata[] = {customerid,customername,meterno,Address,city,Email,Phoneno};
                DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                tblmodel.addRow(tbdata);
            }
             
        }
        catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,ex.toString()); 
           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        printbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        Addcustbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Customer Name", "Meter Number ", "Address", "City", "Email", "Phone Number"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Customer Id");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Customer Name");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Meter Number ");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Address");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("City");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Email");
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Phone Number");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 2010, 830);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        printbtn.setBackground(new java.awt.Color(204, 204, 255));
        printbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        Addcustbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Addcustbtn.setText("Add customer");
        Addcustbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddcustbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1420, Short.MAX_VALUE)
                .addComponent(Addcustbtn)
                .addGap(18, 18, 18)
                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(backbtn)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addcustbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 2010, 100);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Homepage obj=new Homepage();
        obj.setVisible(true);
       // this.hide();
    }//GEN-LAST:event_backbtnActionPerformed

    private void AddcustbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddcustbtnActionPerformed
        // TODO add your handling code here:
     Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
       this.hide();   
    }//GEN-LAST:event_AddcustbtnActionPerformed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customerdetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addcustbtn;
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JButton printbtn;
    // End of variables declaration//GEN-END:variables
}
