
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class Disconnection extends javax.swing.JFrame {
 Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
    /**
     * Creates new form Disconnection
     */
    public Disconnection() {
        initComponents();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Phoneno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestdetail = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Disconnection Request");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(740, 20, 462, 56);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -2, 2100, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Customer Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 310, 240, 42);
        getContentPane().add(customerid);
        customerid.setBounds(930, 220, 180, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 220, 160, 42);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(name);
        name.setBounds(930, 310, 340, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Meter no:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 390, 170, 42);

        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        getContentPane().add(meterno);
        meterno.setBounds(930, 400, 340, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Address:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 480, 150, 42);
        getContentPane().add(address);
        address.setBounds(930, 490, 340, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Phoneno:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 570, 160, 30);

        Phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonenoActionPerformed(evt);
            }
        });
        getContentPane().add(Phoneno);
        Phoneno.setBounds(930, 570, 340, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Request details:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 650, 242, 42);

        requestdetail.setColumns(20);
        requestdetail.setRows(5);
        jScrollPane1.setViewportView(requestdetail);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(930, 650, 340, 90);

        submit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(690, 820, 130, 60);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(900, 820, 130, 60);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1140, 220, 130, 50);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Cancle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 820, 150, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(740, 310, 0, 2);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addcustomer.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -90, 1940, 1110);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1010, 40));

        Addcustomer.setBorder(null);
        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Calculatebill.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DepositeDetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customerdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        meterdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenoActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         try{
         String insert = db.Insert("insert into disconnection(customerid, name, meterno, address, Phoneno, requestdetail)values('"+customerid.getText()+"','"+name.getText().toString()+"','"+meterno.getText()+"','"+address.getText().toString()+"','"+Phoneno.getText().toString()+"','"+requestdetail.getText().toString()+"')");
       JOptionPane.showMessageDialog(null, insert);
        }
       catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex.toString());
        }   
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String delete=db.delete("delete from disconnection where customerid='"+customerid.getText()+"' ");
     JOptionPane.showMessageDialog(null,delete);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from disconnection  where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
               name.setText(rs.getString("name"));
                meterno.setText(rs.getString("meterno"));
                address.setText(rs.getString("address"));
                Phoneno.setText(rs.getString("Phoneno"));
                requestdetail.setText(rs.getString("requestdetail"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Homepage obj=new Homepage();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_meternoKeyPressed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disconnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disconnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disconnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disconnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disconnection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JTextField Phoneno;
    private javax.swing.JTextField address;
    private javax.swing.JTextField customerid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JTextField meterno;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea requestdetail;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
