
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class meterdetails extends javax.swing.JFrame {
  Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
   
    /**
     * Creates new form meterdetails
     */
    public meterdetails() {
        initComponents();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        connectdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        currentrd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        initialrd = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meter Details ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(840, 20, 320, 58);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1960, 98);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText(" Customer Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 250, 230, 42);

        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });
        getContentPane().add(customerid);
        customerid.setBounds(970, 250, 170, 40);

        search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(1160, 250, 110, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText(" Meter Number:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 340, 260, 42);

        meterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meternoMouseClicked(evt);
            }
        });
        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        getContentPane().add(meterno);
        meterno.setBounds(970, 340, 300, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Connection date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 440, 270, 42);
        getContentPane().add(connectdate);
        connectdate.setBounds(970, 440, 300, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Current reading:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 540, 280, 42);

        currentrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentrdActionPerformed(evt);
            }
        });
        getContentPane().add(currentrd);
        currentrd.setBounds(970, 540, 300, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Initial Reading:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 640, 250, 42);

        initialrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialrdActionPerformed(evt);
            }
        });
        getContentPane().add(initialrd);
        initialrd.setBounds(970, 640, 300, 40);

        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(690, 750, 120, 60);

        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(860, 750, 110, 60);

        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setText("Delete ");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1010, 750, 120, 60);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Cancle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1160, 750, 110, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meterdetails.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, -220, 1970, 1350);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1010, 40));

        Addcustomer.setBorder(null);
        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Calculatebill.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DepositeDetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customerdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        meterdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root");
            st=cn.createStatement();
            String sql = "select*from meterdetails where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {

                meterno.setText(rs.getString("meterno"));
                connectdate.setText(rs.getString("connectdate"));
                currentrd.setText(rs.getString("currentrd"));
                initialrd.setText(rs.getString("initialrd"));

            }

        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Homepage obj=new Homepage();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String delete=db.delete("delete from meterdetails where customerid='"+customerid.getText()+"' ");
            JOptionPane.showMessageDialog(null,delete);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            String update = db.update("update meterdetails set customerid='"+customerid.getText().toString()+"',meterno='"+meterno.getText().toString()+"',connectdate='"+connectdate.getText().toString()+"',currentrd='"+currentrd.getText().toString()+"',initialrd='"+initialrd.getText().toString()+"' where  customerid='"+customerid.getText()+"' ");
            JOptionPane.showMessageDialog(null, update);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.toString());

        }
    }//GEN-LAST:event_updateActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            String insert=db.Insert("insert into meterdetails(customerid, meterno, connectdate, currentrd, initialrd)values ('"+customerid.getText().toString()+"','"+meterno.getText().toString()+"','"+connectdate.getText().toString()+"','"+currentrd.getText().toString()+"','"+initialrd.getText().toString()+"')");
            JOptionPane.showMessageDialog(null, insert);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }

    }//GEN-LAST:event_submitActionPerformed

    private void currentrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentrdActionPerformed

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();

        if(Character.isDigit(ch)){
        }
        else{
            JOptionPane.showMessageDialog(null, "Only numbers are allowed!");

        }
    }//GEN-LAST:event_meternoKeyPressed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void meternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meternoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_meternoMouseClicked

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void initialrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meterdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meterdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meterdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meterdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meterdetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JTextField connectdate;
    private javax.swing.JTextField currentrd;
    private javax.swing.JTextField customerid;
    private javax.swing.JButton delete;
    private javax.swing.JTextField initialrd;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JTextField meterno;
    private javax.swing.JButton search;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
