import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naina
 */
public class Paymentdetails extends javax.swing.JFrame {
   Connection cn=null;
   Statement st=null;
   Database db=new Database();
   String result=db.Connectdb();
    /**
     * Creates new form Paymentdetails
     */
    public Paymentdetails() {
        initComponents();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize,ysize-taskBarSize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pick = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        TotalBill = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        paymentmode = new javax.swing.JComboBox();
        Submit = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Addcustomer = new javax.swing.JMenu();
        Calculatebill = new javax.swing.JMenu();
        DepositeDetails = new javax.swing.JMenu();
        Customerdetails = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        meterdetails = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(810, 20, 384, 58);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 2000, 100);

        pick.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pick.setText("Pick");
        pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickActionPerformed(evt);
            }
        });
        getContentPane().add(pick);
        pick.setBounds(1140, 210, 120, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Customer Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 210, 230, 42);

        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });
        getContentPane().add(customerid);
        customerid.setBounds(950, 210, 160, 40);

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(950, 300, 310, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Customer Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 300, 270, 42);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Meter no:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 390, 200, 42);

        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        getContentPane().add(meterno);
        meterno.setBounds(950, 390, 310, 40);

        TotalBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TotalBillKeyPressed(evt);
            }
        });
        getContentPane().add(TotalBill);
        TotalBill.setBounds(950, 480, 310, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Total Bill:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 480, 180, 42);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Status:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 560, 160, 42);

        status.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paid", "Unpaid" }));
        getContentPane().add(status);
        status.setBounds(950, 570, 170, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Payment Mode:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 650, 260, 42);

        paymentmode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        paymentmode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Online", "None" }));
        getContentPane().add(paymentmode);
        paymentmode.setBounds(950, 650, 170, 40);

        Submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(620, 760, 100, 50);

        Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(780, 760, 100, 50);

        Update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(930, 760, 110, 50);

        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(1090, 760, 100, 50);

        Back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(1230, 760, 90, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic1.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 100, 1990, 910);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1010, 40));

        Addcustomer.setBorder(null);
        Addcustomer.setText("Addcustomer");
        Addcustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Addcustomer);

        Calculatebill.setText("Calculatebill");
        Calculatebill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Calculatebill.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Calculatebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatebillMouseClicked(evt);
            }
        });
        jMenuBar2.add(Calculatebill);

        DepositeDetails.setText("DepositeDetails");
        DepositeDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DepositeDetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DepositeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeDetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(DepositeDetails);

        Customerdetails.setText("Customerdetails");
        Customerdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customerdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        Customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customerdetails);

        jMenu1.setText("Paymentdetails");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        meterdetails.setText("meterdetails");
        meterdetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        meterdetails.setMargin(new java.awt.Insets(4, 4, 4, 4));
        meterdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(meterdetails);

        jMenu2.setText("Disconnection");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("complaintregistration");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Homepage obj=new Homepage();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BackActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try{
         String insert = db.Insert("insert into paymentdetails(customerid,name, meterno, totalbill, status,paymentmode)values ('"+customerid.getText()+"','"+name.getText().toString()+"','"+meterno.getText().toString()+"','"+TotalBill.getText().toString()+"','"+status.getSelectedItem().toString()+"','"+paymentmode.getSelectedItem().toString()+"' )");
       JOptionPane.showMessageDialog(null, insert);
        }
       catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex.toString());
        }          
    }//GEN-LAST:event_SubmitActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         try{
          String update = db.update("update paymentdetails set name='"+name.getText().toString()+"',meterno='"+meterno.getText().toString()+"',totalbill='"+TotalBill.getText().toString()+"',status='"+status.getSelectedItem().toString()+"',paymentmode='"+paymentmode.getSelectedItem().toString()+"' where  customerid='"+customerid.getText()+"' ");
          JOptionPane.showMessageDialog(null, update);
      }  
      catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex.toString());
          
      }
                
    }//GEN-LAST:event_UpdateActionPerformed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from paymentdetails where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                name.setText(rs.getString("name"));
                meterno.setText(rs.getString("meterno"));
                TotalBill.setText(rs.getString("Totalbill"));
                status.setSelectedItem(rs.getString("status"));
                paymentmode.setSelectedItem(rs.getString("paymentmode"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }

    }//GEN-LAST:event_SearchActionPerformed

    private void pickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","root"); 
            st=cn.createStatement();
            String sql = "select*from calculatebill where customerid = '"+customerid.getText().toString()+"'";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                name.setText(rs.getString("name"));
                meterno.setText(rs.getString("meterno"));
                TotalBill.setText(rs.getString("Totalbill"));
                  
            }
            
        }
               catch(Exception ex)
               {
                   System.out.println(ex);
               }

    
                           
    }//GEN-LAST:event_pickActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         try
        {
            String delete=db.delete("delete from paymentdetails where customerid='"+customerid.getText()+"' ");
     JOptionPane.showMessageDialog(null,delete);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_meternoKeyPressed

    private void TotalBillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalBillKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    
                }
    }//GEN-LAST:event_TotalBillKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        
                if(Character.isDigit(ch)){
                    JOptionPane.showMessageDialog(null, "Only characters are allowed!");
                }
                else{
                    
                }
    }//GEN-LAST:event_nameKeyPressed

    private void AddcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcustomerMouseClicked
        // TODO add your handling code here:
        Addcustomer obj=new Addcustomer();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AddcustomerMouseClicked

    private void CalculatebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatebillMouseClicked
        // TODO add your handling code here:
        Calculatebill obj=new Calculatebill();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CalculatebillMouseClicked

    private void DepositeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeDetailsMouseClicked
        // TODO add your handling code here:
        DepositeDetails obj=new DepositeDetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_DepositeDetailsMouseClicked

    private void CustomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerdetailsMouseClicked
        // TODO add your handling code here:
        Customerdetails obj=new Customerdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CustomerdetailsMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Paymentdetails obj=new Paymentdetails();
        obj.setVisible(true);
        this.hide();

        // this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void meterdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsMouseClicked
        // TODO add your handling code here:
        meterdetails obj=new meterdetails();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_meterdetailsMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Disconnection obj=new Disconnection();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        complaintregistration obj=new complaintregistration();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paymentdetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Addcustomer;
    private javax.swing.JButton Back;
    private javax.swing.JMenu Calculatebill;
    private javax.swing.JMenu Customerdetails;
    private javax.swing.JButton Delete;
    private javax.swing.JMenu DepositeDetails;
    private javax.swing.JButton Search;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TotalBill;
    private javax.swing.JButton Update;
    private javax.swing.JTextField customerid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu meterdetails;
    private javax.swing.JTextField meterno;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox paymentmode;
    private javax.swing.JButton pick;
    private javax.swing.JComboBox status;
    // End of variables declaration//GEN-END:variables
}
